[tool.poetry]
name = "prefixed-enum"
version = "1.0.0"
description = ""
authors = ["omaera <omaera@otonosei.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
